export const CLOSE_MODAL_WINDOW = 'ENGINE/CLOSE_MODAL_WINDOW';
export const INIT_ENGINE = 'ENGINE/INIT';
export const ON_OFF_MOUSE = 'ENGINE/ON_OFF_MOUSE';
export const MOUSE_MOVE = 'ENGINE/MOUSE_MOVE';
export const ARROW_PRESSED = 'ENGINE/ARROW_PRESSED';
export const SWIPE = 'ENGINE/SWIPE';
export const REVERT = 'ENGINE/REVERT';
